# -*- coding: utf-8 -*-
"""data science.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DYIDH-OPueFujKZ_cPOSjQUJ75NVQdHC
"""

#//   Akshar Anant  //
#//   RA2311030030055  //
#// DATA-SCIENCE ASSIGNMENT 3 //

#Write a Python program to draw line charts of the financial data of Alphabet Inc.
#between October 3, 2016 to October 7, 2016. Sample Financial data (fdata.csv):
# Date,Open,High,Low,Close
# 10-03-16,774.25,776.065002,769.5,772.559998
# 10-04-16,776.030029,778.710022,772.890015,776.429993
# 10-05-16,779.309998,782.070007,775.650024,776.469971
# 10-06-16,779,780.47998,775.539978,776.859985
# 10-07-16,779.659973,779.659973,770.75,775.080017

import pandas as pd
import matplotlib.pyplot as plt
data = {'Date':['10-03-16','10-04-16','10-05-16','10-06-16','10-07-16'],
'Open':[774.25,776.030029,779.309998,779,779.659973],
'High':[776.065002,778.710022,782.070007,780.47998,779.659973],
'Low':[769.5,772.890015,775.650024,775.539978,770.75],
'Close':[772.559998,776.429993,776.469971,776.859985,775.080017]}
df = pd.DataFrame(data)
df.plot(x='Date')
plt.title('Alphabet Inc. Financial Data')
plt.show()

# Question 2 - Write a Python program to Program to show number of students vs marks obtained (Horizontal Bar Plot).
# nos = [2, 9, 20, 25, 30, 39]
# marks = [12, 24, 25, 27,29, 30]

import matplotlib.pyplot as plt
nos = [2, 9, 20, 25, 30, 39]
marks = [12, 24, 25, 27, 29, 30]
plt.barh(marks, nos)
plt.show()

#Example 6: The file "monthsales.csv" have stored the sales (in Rs) made in first six months for four years.
#2018     2019     2020     2021
#2500     2600     2450     3250
#2200     1800     2000     3200
#3000     2500     3000     3800
#2800     3000     3100     2800
#2750     3200     1950     2900
#3500     2000     3550     2300
#/// Year-wise sales of first six months ///
#//Draw the line chart for the data given above with following details.//
#1. Chart title as "Year-Wise Sales"
#2. X-axis label as "Months"
#3. Y-axis label as "Sales"

import matplotlib.pyplot as plt
months = range(1,7)
y2018 = [2500,2200,3000,2800,2750,3500]
y2019 = [2600,1800,2500,3000,3200,2000]
y2020 = [2450,2000,3000,3100,1950,3550]
y2021 = [3250,3200,3800,2800,2900,2300]
plt.plot(months,y2018,label='2018')
plt.plot(months,y2019,label='2019')
plt.plot(months,y2020,label='2020')
plt.plot(months,y2021,label='2021')
plt.title('Year-Wise Sales')
plt.xlabel('Months')
plt.ylabel('Sales')
plt.legend()
plt.show()

# QUE 4 - Assuming the same CSV file, i.e., monthsales.csv,
# plot the line chart with following customisations.
# Chart should have Month name on X-axis instead of numbers.
# Maker =”*” Marker size=10 linestyle=”–“ Linewidth =3

import matplotlib.pyplot as plt
months=['Jan','Feb','Mar','Apr','May','Jun']
y2018=[2500,2200,3000,2800,2750,3500]
y2019=[2600,1800,2500,3000,3200,2000]
y2020=[2450,2000,3000,3100,1950,3550]
y2021=[3250,3200,3800,2800,2900,2300]
plt.plot(months,y2018,marker='*',markersize=10,linestyle='--',linewidth=3,label='2018')
plt.plot(months,y2019,marker='*',markersize=10,linestyle='--',linewidth=3,label='2019')
plt.plot(months,y2020,marker='*',markersize=10,linestyle='--',linewidth=3,label='2020')
plt.plot(months,y2021,marker='*',markersize=10,linestyle='--',linewidth=3,label='2021')
plt.title('Year-Wise Sales')
plt.xlabel('Months')
plt.ylabel('Sales')
plt.legend()
plt.show()

# Anant is working as a Data Analyst in a company named “”Compu-Tech”. He stored the following data in a file named “emp.csv”.
# He wants to present “Department” (First Column) and “No_of_Emp” (Third Column) in a bar chart. Help him to write the code.
# Department              Expenditure (in Rs)              No_of_Emp
# HR                       2500                               40
# Sales                    3000                               30
# Finance                  2200                               35
# Marketing                5100                               32
# IT                       3900                               45

import matplotlib.pyplot as plt
dep=['HR','Sales','Finance','Marketing','IT']
emp=[40,30,35,32,45]
plt.bar(dep,emp,color='red')
plt.title('Compu-Tech Employee Data')
plt.xlabel('Departments')
plt.ylabel('Number of Employees')
plt.show()

#'''(Visit data.gov.in , search for the following in “catalogs” option of the website:
#• Final population Totals, India and states
#• State Wise literacy rate Download them and create a CSV file containing population data and literacy rate of the respective state.
#Also add a column Region to the CSV file that should contain the values East, West, North and South.
#Plot a scatter plot for each region where X axis should be population and Y axis should be Literacy rate.
#Change the marker to a diamond and size as the square root of the literacy rate.
#Group the data on the column region and display a bar chart depicting average literacy rate for each region.)

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

data = {
    'State': ['Uttar Pradesh','Maharashtra','Bihar','West Bengal','Madhya Pradesh','Tamil Nadu','Rajasthan','Karnataka','Gujarat','Andhra Pradesh','Odisha','Telangana','Kerala','Jharkhand','Assam','Punjab','Chhattisgarh','Haryana','Delhi','Jammu and Kashmir','Uttarakhand','Himachal Pradesh','Tripura','Meghalaya','Manipur','Nagaland','Goa','Arunachal Pradesh','Mizoram','Sikkim'],
    'Population': [199812341,112374333,104099452,91276115,72626809,72147030,68548437,61095297,60439692,84580777,41974218,35003674,33406061,32988134,31205576,27743338,25545198,25351462,16787941,12541302,10086292,6864602,3673917,2966889,2570390,1978502,1458545,1383727,1097206,610577],
    'Literacy Rate': [67.68,82.34,61.80,76.26,69.32,80.09,66.11,75.36,78.03,67.02,72.87,66.54,94.00,66.41,72.19,75.84,70.28,75.55,86.21,68.74,78.82,82.80,87.75,74.43,79.85,79.55,88.70,65.38,91.33,81.42],
    'Region': ['North','West','East','East','Central','South','North','South','West','South','East','South','South','East','East','North','Central','North','North','North','North','North','East','East','East','East','West','East','East','East']
}
df = pd.DataFrame(data)

for r in df['Region'].unique():
    d = df[df['Region'] == r]
    plt.scatter(d['Population'], d['Literacy Rate'], marker='D', s=np.sqrt(d['Literacy Rate'])*10)
    plt.title(f'{r} Region')
    plt.xlabel('Population')
    plt.ylabel('Literacy Rate')
    plt.show()

df.groupby('Region')['Literacy Rate'].mean().plot(kind='bar')
plt.title('Average Literacy Rate by Region')
plt.ylabel('Literacy Rate (%)')
plt.show()

#In order to assess the performance of students of a class in the annual examination,
#the class teacher stored marks of the students in all the 5 subjects in a CSV “Marks.csv” file as shown in Table.
#Plot the data using boxplot and perform a comparative analysis of performance in each subject.

#Name              English   Maths   Hindi  Science   Social Studies
#Rishika Batra       95        95      90      94          95

#Waseem Ali          95        76      79       77         89

#Kulpreet Singh      78        81      75       76         88

#Annie Mathews       88        63      67       77         80

import pandas as pd
import matplotlib.pyplot as plt
data = {'English':[95,95,78,88],'Maths':[95,76,81,63],'Hindi':[90,79,75,67],'Science':[94,77,76,77],'Social_Studies':[95,89,88,80]}
df = pd.DataFrame(data)
df.boxplot()
plt.title('Student Performance by Subject')
plt.ylabel('Marks')
plt.show()

'''Write a Python program to create bar plot of scores by group and gender.
Use multiple X values on the same chart for men and women.
Sample Data: Means (men) = (22, 30, 35, 35, 26) Means (women) = (25, 32, 30, 35, 29)'''  # NOTE- [''' REPRESENTS MULTILINE STRINGS EQUIVALENT TO SINGLE/MULTILINE COMMENTS IN PYTHON ].

import numpy as np
import matplotlib.pyplot as plt
men=[22,30,35,35,26]
women=[25,32,30,35,29]
x=np.arange(5)
w=0.35
plt.bar(x-w/2,men,w,color='green',label='Men')
plt.bar(x+w/2,women,w,color='red',label='Women')
plt.xticks(x,['G1','G2','G3','G4','G5'])
plt.legend()
plt.show()

''' QUESTION 9
a. Calculate total sale data for last year for each product and show it using a Pie chart
Note: In pie chart display Number of units sold per year for each product in percentage
b. Read Bathing soap facewash of all months and display it using the Subplot.'''

import pandas as pd
import matplotlib.pyplot as plt
data = {
    'month_number': [1,2,3,4,5,6,7,8,9,10,11,12],
    'facecream': [2500,2630,2140,3400,3600,2760,2980,3700,3540,1990,2340,2900],
    'facewash': [1500,1200,1340,1130,1740,1555,1120,1400,1780,1890,2100,1760],
    'toothpaste': [5200,5100,4550,5870,4560,4890,4780,5860,6100,8300,7300,7400],
    'bathingsoap': [9200,6100,9550,8870,7760,7490,8980,9960,8100,10300,13300,14400],
    'shampoo': [1200,2100,3550,1870,1560,1890,1780,2860,2100,2300,2400,1800],
    'moisturizer': [1500,1200,1340,1130,1740,1555,1120,1400,1780,1890,2100,1760]
}
df = pd.DataFrame(data)
# PART A - DATA TO SHOW FOR Piechart.
# a. Pie chart________________________________________________________________________.
products = ['facecream','facewash','toothpaste','bathingsoap','shampoo','moisturizer']
totals = df[products].sum()
plt.pie(totals, labels=products, autopct='%1.1f%%')
plt.title('Total Units Sold per Product (%)')
plt.show()

#PART B - DATA TO SHOW FOR Subplot.
# b. Subplot__________________________________________________________________________.
plt.subplot(211)
plt.plot(df['month_number'], df['bathingsoap'])
plt.title('Sales data of a Bathingsoap')
plt.subplot(212)
plt.plot(df['month_number'], df['facewash'], color='red')
plt.title('Sales data of a facewash')
plt.show()

'''QUES - 10 Read the total profit of each month and show it using the histogram to see the most common profit ranges.'''

import pandas as pd
import matplotlib.pyplot as plt
data = {
    'month_number': [1,2,3,4,5,6,7,8,9,10,11,12],
    'total_profit': [211000,183300,224700,222700,209600,201400,295500,361400,234000,266700,412800,300200]
}
df = pd.DataFrame(data)
plt.hist(df['total_profit'])
plt.title('Profit data')
plt.xlabel('profit range in dollar')
plt.ylabel('Actual Profit in dollar')
plt.legend(['Profit data'])
plt.show()

